CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Email NVARCHAR(200) NULL,
    Phone NVARCHAR(20) NULL,
    PasswordHash NVARCHAR(200) NULL,
    IsEmailVerified BIT NOT NULL DEFAULT 0,
    IsPhoneVerified BIT NOT NULL DEFAULT 0,
    IsAdmin BIT NOT NULL DEFAULT 0,
    Status INT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LastLoginAtUtc DATETIME2 NULL
);

CREATE UNIQUE INDEX IX_Users_Email ON Users(Email) WHERE Email IS NOT NULL;
CREATE UNIQUE INDEX IX_Users_Phone ON Users(Phone) WHERE Phone IS NOT NULL;

CREATE TABLE Wallets (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Currency NVARCHAR(3) NOT NULL DEFAULT 'PTS',
    Balance DECIMAL(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_Wallets_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE WalletTransactions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    WalletId UNIQUEIDENTIFIER NOT NULL,
    Type INT NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Reason NVARCHAR(200) NOT NULL,
    Reference NVARCHAR(100) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_WalletTransactions_Wallets FOREIGN KEY (WalletId) REFERENCES Wallets(Id)
);

CREATE INDEX IX_WalletTransactions_CreatedAtUtc ON WalletTransactions(CreatedAtUtc DESC);

CREATE TABLE OtpRequests (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Phone NVARCHAR(20) NOT NULL,
    CodeHash NVARCHAR(200) NOT NULL,
    Purpose NVARCHAR(50) NOT NULL,
    ExpiresAtUtc DATETIME2 NOT NULL,
    IsUsed BIT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Games (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    ShortDescription NVARCHAR(400) NOT NULL,
    BannerUrl NVARCHAR(400) NULL,
    Status INT NOT NULL DEFAULT 0,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE INDEX IX_Games_SortOrder ON Games(SortOrder);

CREATE TABLE ContentPages (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Slug NVARCHAR(100) NOT NULL,
    Title NVARCHAR(150) NOT NULL,
    Body NVARCHAR(MAX) NOT NULL,
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE UNIQUE INDEX IX_ContentPages_Slug ON ContentPages(Slug);

CREATE TABLE Banners (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Headline NVARCHAR(200) NOT NULL,
    Subheadline NVARCHAR(400) NOT NULL,
    ImageUrl NVARCHAR(400) NULL,
    CtaText NVARCHAR(200) NULL,
    CtaLink NVARCHAR(200) NULL,
    SortOrder INT NOT NULL DEFAULT 0
);

CREATE TABLE AuditLogs (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ActorUserId UNIQUEIDENTIFIER NULL,
    Action NVARCHAR(100) NOT NULL,
    Summary NVARCHAR(500) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE PaymentRecords (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Provider NVARCHAR(100) NOT NULL,
    ProviderOrderId NVARCHAR(100) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Status INT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CompletedAtUtc DATETIME2 NULL
);
