CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Email NVARCHAR(200) NULL,
    Phone NVARCHAR(20) NULL,
    PasswordHash NVARCHAR(200) NULL,
    IsEmailVerified BIT NOT NULL DEFAULT 0,
    IsPhoneVerified BIT NOT NULL DEFAULT 0,
    IsAdmin BIT NOT NULL DEFAULT 0,
    Status INT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LastLoginAtUtc DATETIME2 NULL
);

CREATE UNIQUE INDEX IX_Users_Email ON Users(Email) WHERE Email IS NOT NULL;
CREATE UNIQUE INDEX IX_Users_Phone ON Users(Phone) WHERE Phone IS NOT NULL;

CREATE TABLE Wallets (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Currency NVARCHAR(3) NOT NULL DEFAULT 'PTS',
    Balance DECIMAL(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_Wallets_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE WalletTransactions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    WalletId UNIQUEIDENTIFIER NOT NULL,
    Type INT NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Reason NVARCHAR(200) NOT NULL,
    Reference NVARCHAR(100) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_WalletTransactions_Wallets FOREIGN KEY (WalletId) REFERENCES Wallets(Id)
);

CREATE INDEX IX_WalletTransactions_CreatedAtUtc ON WalletTransactions(CreatedAtUtc DESC);

CREATE TABLE OtpRequests (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Phone NVARCHAR(20) NOT NULL,
    CodeHash NVARCHAR(200) NOT NULL,
    Purpose NVARCHAR(50) NOT NULL,
    ExpiresAtUtc DATETIME2 NOT NULL,
    IsUsed BIT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Games (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    ShortDescription NVARCHAR(400) NOT NULL,
    BannerUrl NVARCHAR(400) NULL,
    CategoryId UNIQUEIDENTIFIER NOT NULL,
    Status INT NOT NULL DEFAULT 0,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE INDEX IX_Games_SortOrder ON Games(SortOrder);

CREATE TABLE Categories (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(80) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IX_Categories_Name ON Categories(Name);
CREATE INDEX IX_Categories_SortOrder ON Categories(SortOrder);

ALTER TABLE Games
ADD CONSTRAINT FK_Games_Categories
FOREIGN KEY (CategoryId) REFERENCES Categories(Id);

CREATE TABLE ContentPages (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Slug NVARCHAR(100) NOT NULL,
    Title NVARCHAR(150) NOT NULL,
    Body NVARCHAR(MAX) NOT NULL,
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE UNIQUE INDEX IX_ContentPages_Slug ON ContentPages(Slug);

CREATE TABLE Banners (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Headline NVARCHAR(200) NOT NULL,
    Subheadline NVARCHAR(400) NOT NULL,
    ImageUrl NVARCHAR(400) NULL,
    CtaText NVARCHAR(200) NULL,
    CtaLink NVARCHAR(200) NULL,
    SortOrder INT NOT NULL DEFAULT 0
);

CREATE TABLE AuditLogs (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ActorUserId UNIQUEIDENTIFIER NULL,
    Action NVARCHAR(100) NOT NULL,
    Summary NVARCHAR(500) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE PaymentRecords (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Provider NVARCHAR(100) NOT NULL,
    ProviderOrderId NVARCHAR(100) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Status INT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CompletedAtUtc DATETIME2 NULL
);

CREATE TABLE CrashGameRounds (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    RoundNumber BIGINT NOT NULL,
    Status INT NOT NULL DEFAULT 0,
    ServerSeed NVARCHAR(128) NOT NULL,
    ServerSeedHash NVARCHAR(128) NOT NULL,
    ClientSeed NVARCHAR(128) NOT NULL,
    Nonce BIGINT NOT NULL,
    CrashMultiplier DECIMAL(10,2) NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    StartedAtUtc DATETIME2 NULL,
    EndedAtUtc DATETIME2 NULL
);

CREATE UNIQUE INDEX IX_CrashGameRounds_RoundNumber ON CrashGameRounds(RoundNumber);
CREATE INDEX IX_CrashGameRounds_EndedAtUtc ON CrashGameRounds(EndedAtUtc DESC);

CREATE TABLE CrashBets (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    RoundId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    BetAmount DECIMAL(18,2) NOT NULL,
    TargetMultiplier DECIMAL(10,2) NULL,
    CashoutMultiplier DECIMAL(10,2) NULL,
    WinAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
    Status INT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CashedOutAtUtc DATETIME2 NULL,
    CONSTRAINT FK_CrashBets_Rounds FOREIGN KEY (RoundId) REFERENCES CrashGameRounds(Id),
    CONSTRAINT FK_CrashBets_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE INDEX IX_CrashBets_RoundId ON CrashBets(RoundId);
CREATE INDEX IX_CrashBets_UserId ON CrashBets(UserId);
